import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { asociaciones_pages } from "./asociaciones.pages.ts";
import { asociaciones_tables } from "./asociaciones.tables.ts";
import { apply_interaccion_to_row } from "./asociaciones-interaccion.utils.ts";

export const asociaciones_module = define_module({
  resource: "asociaciones",
  labels: {
    singular: "Gestión de asociaciones",
    plural: "Gestión de asociaciones",
    read: "Ver Gestión de asociaciones",
    write: "Editar Gestión de asociaciones",
  },
  routes: define_crud({
    resource: "asociaciones",
    table: "asociaciones",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "asociaci",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      telefono: { type: "string", search: true },
      correo: { type: "string", search: true },
      ciudad: { type: "string", search: true },
      localidad: { type: "string", search: true },
      tipo: { type: "string", search: true },
      fecha: { type: "string", search: true },
      fecha_interaccion: { type: "string", search: true },
      tipo_interaccion: { type: "string", search: true },
      notas_interaccion: { type: "string", search: true },
      notas: { type: "string", search: true },
      pais: { type: "string", search: true },
      interacciones: { type: "json" },
      observaciones: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
    hooks: {
      before_create: (_ctx, row) => apply_interaccion_to_row(row),
      before_update: (_ctx, _id, patch, existing) =>
        apply_interaccion_to_row(patch, existing.interacciones),
    },
  }),
  tables: asociaciones_tables,
  pages: asociaciones_pages,
  menu: [
    {
      id: "control-emergencias.directorio-contactos",
      label: "Directorio de contactos",
      order: 0,
      pageId: "control-emergencias.directorio-contactos",
      path: "directorio-contactos",
      permission: "subject.control-emergencias.directorio-contactos.read",
      icon: "document",
    },
    {
      id: "control-emergencias.categoria-directorio-contactos",
      label: "Categorías del directorio",
      order: 10,
      pageId: "control-emergencias.categoria-directorio-contactos",
      path: "categoria-directorio-contactos",
      permission: "subject.control-emergencias.categoria-directorio-contactos.read",
      icon: "document",
    },
    {
      id: "control-emergencias.voluntariado",
      label: "Gestión de voluntariado",
      order: 1,
      pageId: "control-emergencias.voluntariado",
      path: "voluntariado",
      permission: "subject.control-emergencias.voluntariado.read",
      icon: "document",
    },
    {
      id: "control-emergencias.rescate-animal",
      label: "Rescate animal",
      order: 2,
      pageId: "control-emergencias.rescate-animal",
      path: "rescate-animal",
      permission: "subject.control-emergencias.rescate-animal.read",
      icon: "document",
    },
    {
      id: "control-emergencias.servicios-realizados",
      label: "Servicios realizados",
      order: 3,
      pageId: "control-emergencias.servicios-realizados",
      path: "servicios-realizados",
      permission: "subject.control-emergencias.servicios-realizados.read",
      icon: "document",
    },
    {
      id: "control-emergencias.inventario-sanitario",
      label: "Inventario sanitario",
      order: 4,
      pageId: "control-emergencias.inventario-sanitario",
      path: "inventario-sanitario",
      permission: "subject.control-emergencias.inventario-sanitario.read",
      icon: "document",
    },
    {
      id: "control-emergencias.inventario-general",
      label: "Inventario general",
      order: 5,
      pageId: "control-emergencias.inventario-general",
      path: "inventario-general",
      permission: "subject.control-emergencias.inventario-general.read",
      icon: "document",
    },
    {
      id: "control-emergencias.despensa-solidaria",
      label: "Despensa solidaria",
      order: 6,
      pageId: "control-emergencias.despensa-solidaria",
      path: "despensa-solidaria",
      permission: "subject.control-emergencias.despensa-solidaria.read",
      icon: "document",
    },
    {
      id: "control-emergencias.asociaciones",
      label: "Gestión de asociaciones",
      order: 7,
      pageId: "control-emergencias.asociaciones",
      path: "asociaciones",
      permission: "subject.control-emergencias.asociaciones.read",
      icon: "document",
    },
    {
      id: "control-emergencias.libro-cuentas",
      label: "Libro de cuentas",
      order: 8,
      pageId: "control-emergencias.libro-cuentas",
      path: "libro-cuentas",
      permission: "subject.control-emergencias.libro-cuentas.read",
      icon: "document",
    },
    {
      id: "control-emergencias.registro-emergencias",
      label: "Registro de emergencias",
      order: 9,
      pageId: "control-emergencias.registro-emergencias",
      path: "registro-emergencias",
      permission: "subject.control-emergencias.registro-emergencias.read",
      icon: "document",
    }
    ],
});
