import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { voluntariado_pages } from "./voluntariado.pages.ts";
import { voluntariado_tables } from "./voluntariado.tables.ts";

export const voluntariado_module = define_module({
  resource: "voluntariado",
  labels: {
    singular: "Gestión de voluntariado",
    plural: "Gestión de voluntariado",
    read: "Ver Gestión de voluntariado",
    write: "Editar Gestión de voluntariado",
  },
  routes: define_crud({
    resource: "voluntariado",
    table: "voluntariado",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "voluntar",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      numero_socio: { type: "string", search: true },
      indicativo: { type: "string", search: true },
      estado: { type: "string", search: true },
      documento_identidad: { type: "string", search: true },
      telefono: { type: "string", search: true },
      correo: { type: "string", search: true },
      localidad: { type: "string", search: true },
      foto: { type: "string", search: true },
      fecha_ingreso: { type: "string", search: true },
      fecha_nacimiento: { type: "string", search: true },
      direccion_postal: { type: "string", search: true },
      codigo_postal: { type: "string", search: true },
      formacion_interes: { type: "json" },
      otra_formacion: { type: "string", search: true },
      carnet_conducir: { type: "string", search: true },
      observaciones: { type: "string", search: true },
      documentos_adjuntos: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: voluntariado_tables,
  pages: voluntariado_pages,
  menu: [],
});
