import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-control-emergencias";

export const voluntariado_pages: KirletPageDecl[] = [
  {
    id: "control-emergencias.voluntariado",
    path: "voluntariado",
    permission: "subject.control-emergencias.voluntariado.read",
    build: () =>
      build_feature_shell_page({
        id: "control-emergencias.voluntariado",
        owner: "subject-control-emergencias",
        title: "Gestión de voluntariado",
        props: {
          basePath: "voluntariado",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Gestión de voluntariado",
            subtitle: "Submenú de control-emergencias",
            pluralLabel: "gestión de voluntariado",
            singularLabel: "gestión de voluntariado",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/voluntariado`,
            record: `${API}/voluntariado/:id`,
            create: { method: "POST", action: `${API}/voluntariado` },
            update: { method: "PATCH", action: `${API}/voluntariado/:id` },
            delete: { method: "DELETE", action: `${API}/voluntariado/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "numero_socio", label: "numero socio", sortable: true, priority: 3 },
              { key: "indicativo", label: "indicativo", sortable: true, priority: 3 },
              { key: "estado", label: "estado", sortable: true, priority: 3 },
              { key: "documento_identidad", label: "documento identidad", sortable: true, priority: 3 },
              { key: "telefono", label: "telefono", sortable: true, priority: 3 },
              { key: "correo", label: "correo", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "numero_socio", component: "input-text", label: "numero socio" },
              { name: "indicativo", component: "input-text", label: "indicativo" },
              { name: "estado", component: "input-text", label: "estado" },
              { name: "documento_identidad", component: "input-text", label: "documento identidad" },
              { name: "telefono", component: "input-text", label: "telefono", type: "tel" },
              { name: "correo", component: "input-text", label: "correo", type: "email" },
              { name: "localidad", component: "input-text", label: "localidad" },
              { name: "foto", component: "input-image", label: "foto" },
              { name: "fecha_ingreso", component: "input-date", label: "fecha ingreso" },
              { name: "fecha_nacimiento", component: "input-date", label: "fecha nacimiento" },
              { name: "direccion_postal", component: "input-text", label: "direccion postal" },
              { name: "codigo_postal", component: "input-mask", label: "codigo postal", mask: "00000" },
              {
                name: "formacion_interes",
                component: "input-checkbox-group",
                label: "formacion interes",
                options: [
                  { value: "tes", label: "TES" },
                  { value: "tts", label: "TTS" },
                  { value: "primeros_auxilios", label: "Primeros auxilios" },
                  { value: "atencion_psicologica", label: "Atención psicológica" },
                  { value: "conduccion_4x4", label: "Conducción 4x4" },
                  { value: "medicina", label: "Medicina" },
                  { value: "enfermeria", label: "Enfermería" },
                  { value: "svb_desa", label: "SVB + DESA" },
                  { value: "piloto_drones", label: "Piloto de drones" },
                  { value: "manejo_emisora", label: "Manejo de emisora" },
                  { value: "tec_proteccion_civil", label: "Téc. protección civil" },
                  { value: "rescate_montana", label: "Rescate en montaña" },
                  { value: "rescate_acuatico", label: "Rescate acuático" },
                  { value: "patron_embarcaciones", label: "Patrón de embarcaciones" },
                  { value: "otros", label: "Otros" },
                ],
              },
              { name: "otra_formacion", component: "input-textarea", label: "otra formacion" },
              { name: "carnet_conducir", component: "input-text", label: "carnet conducir" },
              { name: "observaciones", component: "input-textarea", label: "observaciones" },
              { name: "documentos_adjuntos", component: "input-image", label: "documentos adjuntos", multiple: true },
            ],
          },
        },
      }),
  },
];
