import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-control-emergencias";

export const registro_emergencias_pages: KirletPageDecl[] = [
  {
    id: "control-emergencias.registro-emergencias",
    path: "registro-emergencias",
    permission: "subject.control-emergencias.registro-emergencias.read",
    build: () =>
      build_feature_shell_page({
        id: "control-emergencias.registro-emergencias",
        owner: "subject-control-emergencias",
        title: "Registro de emergencias",
        props: {
          basePath: "registro-emergencias",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Registro de emergencias",
            subtitle: "Submenú de control-emergencias",
            pluralLabel: "registro de emergencias",
            singularLabel: "registro de emergencias",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/registro-emergencias`,
            record: `${API}/registro-emergencias/:id`,
            create: { method: "POST", action: `${API}/registro-emergencias` },
            update: { method: "PATCH", action: `${API}/registro-emergencias/:id` },
            delete: { method: "DELETE", action: `${API}/registro-emergencias/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "fecha_hora_recepcion", label: "fecha hora recepcion", sortable: true, priority: 3 },
              { key: "tipo_emergencia", label: "tipo emergencia", sortable: true, priority: 3 },
              { key: "prioridad", label: "prioridad", sortable: true, priority: 3 },
              { key: "municipio", label: "municipio", sortable: true, priority: 3 },
              { key: "resultado", label: "resultado", sortable: true, priority: 3 },
              { key: "telefono", label: "telefono", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-text", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "fecha_hora_recepcion", component: "input-text", label: "fecha hora recepcion" },
              { name: "tipo_emergencia", component: "input-text", label: "tipo emergencia" },
              { name: "prioridad", component: "input-text", label: "prioridad" },
              { name: "municipio", component: "input-text", label: "municipio" },
              { name: "resultado", component: "input-text", label: "resultado" },
              { name: "telefono", component: "input-text", label: "telefono" },
              { name: "operador", component: "input-text", label: "operador" },
              { name: "duracion_llamada", component: "input-number", label: "duracion llamada" },
              { name: "alertante_nombre", component: "input-text", label: "alertante nombre" },
              { name: "alertante_telefono", component: "input-text", label: "alertante telefono" },
              { name: "direccion_exacta", component: "input-text", label: "direccion exacta" },
              { name: "provincia", component: "input-text", label: "provincia" },
              { name: "coordenadas_gps", component: "input-json", label: "coordenadas gps" },
              { name: "punto_referencia", component: "input-text", label: "punto referencia" },
              { name: "descripcion_inicial", component: "input-text", label: "descripcion inicial" },
              { name: "num_afectados", component: "input-number", label: "num afectados" },
              { name: "existencia_heridos", component: "input-checkbox", label: "existencia heridos" },
              { name: "victimas_mortales", component: "input-checkbox", label: "victimas mortales" },
              { name: "presencia_menores", component: "input-checkbox", label: "presencia menores" },
              { name: "riesgos_anadidos", component: "input-json", label: "riesgos anadidos" },
              { name: "hora_movilizacion", component: "input-text", label: "hora movilizacion" },
              { name: "hora_llegada", component: "input-text", label: "hora llegada" },
              { name: "indicativos_vehiculos", component: "input-text", label: "indicativos vehiculos" },
              { name: "personal_voluntario_activado", component: "input-number", label: "personal voluntario activado" },
              { name: "material_especifico", component: "input-text", label: "material especifico" },
              { name: "recursos_externos", component: "input-json", label: "recursos externos" },
              { name: "instrucciones_alertante", component: "input-text", label: "instrucciones alertante" },
              { name: "consejos_autoproteccion", component: "input-text", label: "consejos autoproteccion" },
              { name: "seguimiento_telefonico", component: "input-checkbox", label: "seguimiento telefonico" },
              { name: "coordinacion_entidades", component: "input-text", label: "coordinacion entidades" },
              { name: "observaciones_operador", component: "input-text", label: "observaciones operador" },
              { name: "hora_finalizacion", component: "input-text", label: "hora finalizacion" },
              { name: "responsable_cierre", component: "input-text", label: "responsable cierre" },
              { name: "necesidad_seguimiento", component: "input-checkbox", label: "necesidad seguimiento" },
              { name: "resumen_final", component: "input-text", label: "resumen final" },
              { name: "adjuntos", component: "input-json", label: "adjuntos" },
            ],
          },
        },
      }),
  },
];
