import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { registro_emergencias_pages } from "./registro-emergencias.pages.ts";
import { registro_emergencias_tables } from "./registro-emergencias.tables.ts";

export const registro_emergencias_module = define_module({
  resource: "registro-emergencias",
  labels: {
    singular: "Registro de emergencias",
    plural: "Registro de emergencias",
    read: "Ver Registro de emergencias",
    write: "Editar Registro de emergencias",
  },
  routes: define_crud({
    resource: "registro-emergencias",
    table: "registro_emergencias",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "registro",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      fecha_hora_recepcion: { type: "string", search: true },
      tipo_emergencia: { type: "string", search: true },
      prioridad: { type: "string", search: true },
      municipio: { type: "string", search: true },
      resultado: { type: "string", search: true },
      telefono: { type: "string", search: true },
      operador: { type: "string", search: true },
      duracion_llamada: { type: "number" },
      alertante_nombre: { type: "string", search: true },
      alertante_telefono: { type: "string", search: true },
      direccion_exacta: { type: "string", search: true },
      provincia: { type: "string", search: true },
      coordenadas_gps: { type: "json" },
      punto_referencia: { type: "string", search: true },
      descripcion_inicial: { type: "string", search: true },
      num_afectados: { type: "number" },
      existencia_heridos: { type: "boolean" },
      victimas_mortales: { type: "boolean" },
      presencia_menores: { type: "boolean" },
      riesgos_anadidos: { type: "json" },
      hora_movilizacion: { type: "string", search: true },
      hora_llegada: { type: "string", search: true },
      indicativos_vehiculos: { type: "string", search: true },
      personal_voluntario_activado: { type: "number" },
      material_especifico: { type: "string", search: true },
      recursos_externos: { type: "json" },
      instrucciones_alertante: { type: "string", search: true },
      consejos_autoproteccion: { type: "string", search: true },
      seguimiento_telefonico: { type: "boolean" },
      coordinacion_entidades: { type: "string", search: true },
      observaciones_operador: { type: "string", search: true },
      hora_finalizacion: { type: "string", search: true },
      responsable_cierre: { type: "string", search: true },
      necesidad_seguimiento: { type: "boolean" },
      resumen_final: { type: "string", search: true },
      adjuntos: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: registro_emergencias_tables,
  pages: registro_emergencias_pages,
  menu: [],
});
