import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const registro_emergencias_tables: KirletTableDecl[] = [
  {
    name: "registro_emergencias",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "fecha_hora_recepcion", type: "text" },
      { name: "tipo_emergencia", type: "text" },
      { name: "prioridad", type: "text" },
      { name: "municipio", type: "text" },
      { name: "resultado", type: "text" },
      { name: "telefono", type: "text" },
      { name: "operador", type: "text" },
      { name: "duracion_llamada", type: "real" },
      { name: "alertante_nombre", type: "text" },
      { name: "alertante_telefono", type: "text" },
      { name: "direccion_exacta", type: "text" },
      { name: "provincia", type: "text" },
      { name: "coordenadas_gps", type: "json" },
      { name: "punto_referencia", type: "text" },
      { name: "descripcion_inicial", type: "text" },
      { name: "num_afectados", type: "real" },
      { name: "existencia_heridos", type: "boolean" },
      { name: "victimas_mortales", type: "boolean" },
      { name: "presencia_menores", type: "boolean" },
      { name: "riesgos_anadidos", type: "json" },
      { name: "hora_movilizacion", type: "text" },
      { name: "hora_llegada", type: "text" },
      { name: "indicativos_vehiculos", type: "text" },
      { name: "personal_voluntario_activado", type: "real" },
      { name: "material_especifico", type: "text" },
      { name: "recursos_externos", type: "json" },
      { name: "instrucciones_alertante", type: "text" },
      { name: "consejos_autoproteccion", type: "text" },
      { name: "seguimiento_telefonico", type: "boolean" },
      { name: "coordinacion_entidades", type: "text" },
      { name: "observaciones_operador", type: "text" },
      { name: "hora_finalizacion", type: "text" },
      { name: "responsable_cierre", type: "text" },
      { name: "necesidad_seguimiento", type: "boolean" },
      { name: "resumen_final", type: "text" },
      { name: "adjuntos", type: "json" },
    ],
    indexes: [
      { name: "idx_registro_emergencias_name", columns: ["name"] },
      { name: "idx_registro_emergencias_active", columns: ["is_active"] },
    ],
  },
];
